[package]
name = "mckendree-lib"
version = "0.1.0"
authors = ["Călin Ardelean <mmn80cpu@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.2"
sled = "0.34.6"
zerocopy = "0.3.0"
byteorder = "1.4.2"